[project]
name = "try-ms-automation-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mss>=10.1.0",
    "pyautogui>=0.9.54",
    "pygetwindow>=0.0.9",
]
